apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-job-cleaner
  labels:
    application: kube-job-cleaner
    version: "0.1"
spec:
  schedule: "17 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            application: kube-job-cleaner
            version: "0.1"
        spec:
          serviceAccountName: job-cleaner
          restartPolicy: OnFailure
          containers:
          - name: cleaner
            image: "envisia/kube-job-cleaner"
            resources:
              limits:
                cpu: 200m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 50Mi
